# Generated by Django 4.2.2 on 2023-07-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('image', models.ImageField(upload_to='image/')),
                ('ingredients', models.CharField(max_length=300, verbose_name='Ингредиенты')),
                ('calories', models.IntegerField()),
                ('steps', models.TextField(verbose_name='Шаги приготовления')),
                ('time_cooking', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('dessert', 'DESSERT'), ('drink', 'DRINK')], default='breakfast', max_length=9)),
                ('online', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
