# Generated by Django 4.1.1 on 2023-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название блюда')),
                ('image', models.ImageField(upload_to='image/')),
                ('ingredients', models.CharField(max_length=50, verbose_name='Ингредиенты')),
                ('calories', models.IntegerField()),
                ('steps', models.TextField(verbose_name='Шаги приготовления')),
                ('time_cooking', models.IntegerField()),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
