# Generated by Django 4.1.1 on 2023-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('dessert', 'DESSERT'), ('drink', 'DRINK')], default='breakfast', max_length=9),
        ),
    ]
