# Generated by Django 4.2.14 on 2024-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_favorite_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_cooking',
            field=models.CharField(max_length=30, verbose_name='Время приготовления'),
        ),
    ]
