# Generated by Django 4.2.14 on 2024-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_time_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_cooking',
            field=models.IntegerField(default=40),
        ),
    ]
